export const FILE_STORAGE_REPOSITORY = Symbol("FILE_STORAGE_REPOSITORY");
export const OBJECT_STORAGE_PORT = Symbol("OBJECT_STORAGE_PORT");
export const MALWARE_SCANNER_PORT = Symbol("MALWARE_SCANNER_PORT");
export const FILE_CONTENT_INSPECTOR_PORT = Symbol(
  "FILE_CONTENT_INSPECTOR_PORT",
);
