import { COURSE_MANAGEMENT_POLICY_NAMES } from "@/modules/course-management/domain/course-management.policy-names";
import { ENROLLMENT_POLICY_NAMES } from "@/modules/enrollment/domain/enrollment.policy-names";

export const ACADEMIC_POLICY_NAMES = {
  PROGRAM_READ: COURSE_MANAGEMENT_POLICY_NAMES.PROGRAM_READ,
  PROGRAM_MANAGE: COURSE_MANAGEMENT_POLICY_NAMES.PROGRAM_MANAGE,
  ACADEMIC_YEAR_READ: COURSE_MANAGEMENT_POLICY_NAMES.TERM_READ,
  ACADEMIC_YEAR_MANAGE: COURSE_MANAGEMENT_POLICY_NAMES.TERM_MANAGE,
  ACADEMIC_TERM_READ: COURSE_MANAGEMENT_POLICY_NAMES.TERM_READ,
  ACADEMIC_TERM_MANAGE: COURSE_MANAGEMENT_POLICY_NAMES.TERM_MANAGE,
  ACADEMIC_SESSION_READ: COURSE_MANAGEMENT_POLICY_NAMES.ACADEMIC_SESSION_READ,
  ACADEMIC_SESSION_MANAGE:
    COURSE_MANAGEMENT_POLICY_NAMES.ACADEMIC_SESSION_MANAGE,
  STUDENT_BATCH_READ: COURSE_MANAGEMENT_POLICY_NAMES.STUDENT_BATCH_READ,
  STUDENT_BATCH_MANAGE: COURSE_MANAGEMENT_POLICY_NAMES.STUDENT_BATCH_MANAGE,
  COURSE_READ: COURSE_MANAGEMENT_POLICY_NAMES.COURSE_READ,
  COURSE_MANAGE: COURSE_MANAGEMENT_POLICY_NAMES.COURSE_MANAGE,
  OFFERING_READ: COURSE_MANAGEMENT_POLICY_NAMES.OFFERING_READ,
  OFFERING_MANAGE: COURSE_MANAGEMENT_POLICY_NAMES.OFFERING_MANAGE,
  COURSE_OUTLINE_READ: COURSE_MANAGEMENT_POLICY_NAMES.COURSE_OUTLINE_READ,
  COURSE_OUTLINE_WRITE: COURSE_MANAGEMENT_POLICY_NAMES.COURSE_OUTLINE_WRITE,
  COURSE_OUTLINE_SUBMIT: COURSE_MANAGEMENT_POLICY_NAMES.COURSE_OUTLINE_SUBMIT,
  COURSE_OUTLINE_COORDINATOR_REVIEW:
    COURSE_MANAGEMENT_POLICY_NAMES.COURSE_OUTLINE_COORDINATOR_REVIEW,
  COURSE_OUTLINE_RETURN_FOR_CORRECTION:
    COURSE_MANAGEMENT_POLICY_NAMES.COURSE_OUTLINE_RETURN_FOR_CORRECTION,
  COURSE_OUTLINE_APPROVE:
    COURSE_MANAGEMENT_POLICY_NAMES.COURSE_OUTLINE_APPROVE,
  COURSE_OUTLINE_ACTIVATE:
    COURSE_MANAGEMENT_POLICY_NAMES.COURSE_OUTLINE_ACTIVATE,
  CURRICULUM_BINDING_MANAGE:
    COURSE_MANAGEMENT_POLICY_NAMES.CURRICULUM_BINDING_MANAGE,
  SYLLABUS_BINDING_MANAGE:
    COURSE_MANAGEMENT_POLICY_NAMES.SYLLABUS_BINDING_MANAGE,
  STUDENT_BATCH_BINDING_MANAGE:
    COURSE_MANAGEMENT_POLICY_NAMES.STUDENT_BATCH_BINDING_MANAGE,
  BATCH_COORDINATOR_ASSIGNMENT_MANAGE:
    COURSE_MANAGEMENT_POLICY_NAMES.BATCH_COORDINATOR_ASSIGNMENT_MANAGE,
  CURRICULUM_VERSION_LIFECYCLE_MANAGE:
    COURSE_MANAGEMENT_POLICY_NAMES.CURRICULUM_VERSION_LIFECYCLE_MANAGE,
  SYLLABUS_VERSION_MANAGE:
    COURSE_MANAGEMENT_POLICY_NAMES.SYLLABUS_VERSION_MANAGE,
  SYLLABUS_VERSION_LIFECYCLE_MANAGE:
    COURSE_MANAGEMENT_POLICY_NAMES.SYLLABUS_VERSION_LIFECYCLE_MANAGE,
  STUDENT_CURRICULUM_ASSIGNMENT_MANAGE:
    COURSE_MANAGEMENT_POLICY_NAMES.STUDENT_CURRICULUM_ASSIGNMENT_MANAGE,
  TEACHER_ASSIGNMENT_MANAGE:
    COURSE_MANAGEMENT_POLICY_NAMES.TEACHER_ASSIGNMENT_MANAGE,
  ENROLLMENT_READ: ENROLLMENT_POLICY_NAMES.RECORD_READ,
  ENROLLMENT_CREATE: ENROLLMENT_POLICY_NAMES.RECORD_CREATE,
  ENROLLMENT_UPDATE: ENROLLMENT_POLICY_NAMES.RECORD_UPDATE,
  ENROLLMENT_SELF_REQUEST: ENROLLMENT_POLICY_NAMES.RECORD_SELF_REQUEST,
} as const;
